### ISSUE TITLE
Why does UniswapV3Pool.sol use NoDelegateCall.sol? 

### ISSUE THREAD

**Issue by elshan-eth** [Uniswap/v3-core#523]
Why does UniswapV3Pool.sol use NoDelegateCall.sol? 

If you use Minimal Proxy instead of NoDelegateCall, you can save gas when deploying a new pool.

Thank you!

**Comment by zemse** [comment]
Possible reasons I think:
- It doesn't use Minimal Proxy for deploying UniswapV3Pool in the protocol itself because swaps would cost an additional DELEGATECALL cost in swaps and operations. If deployment of a pool consumes 4,557,548 gas ([tx](https://etherscan.io/tx/0xdeb368592f3de0f2840754bce61d2c3f29cdb3407c63c699052e68a854c71eaa)), and cost for extra delegate call is 700 then after 4,557,548/700 = 6511 swaps, overall the protocol would be more costly. Hence the costly deployment of the contract makes sense (assuming the pool would be useful enough to cross at least 6511 number of transactions on it).
- NoDelegateCall might be used to prevent easy Uniswap forks.

**Comment by 7779043** [comment]
۵٪×۷۹۹=\\۴۴۴۸۶۵۴=۶۷۸%

**Comment by elshan-eth** [comment]
If we use minimal proxy and calculate the fee at the gas price of 100 gwei, we will get this data: 

The fee will be rise on 0.00007 ETH (~0.22 USD) for the user. But the fee for deployment will drop from ~0.456 ETH (~1409 USD) to ~0.05 ETH (~154.5 USD).
