### ISSUE TITLE
First mint issue with a fee-on-transfer token

### ISSUE THREAD

**Issue by vovapwn** [Uniswap/v3-core#565]
I just created USDC-PAXG (gold stable) v3 Pool.
**creation tx:**
https://etherscan.io/tx/0xe6f7342a898f2ee09e68b31384240cbc48bf18a7e14705c037536afae4166277
**Pool contract:**
https://etherscan.io/address/0x5ae13baaef0620fdae1d355495dc51a17adb4082#code
It even appeared in the interface:
![image](https://user-images.githubusercontent.com/96361013/173957898-2f9b5b15-06a1-46bf-9069-8950e0712a0a.png)
But when I try to mint first liquidity, nothing happens. Interface is not working, and when I send tx manually, it fails.
**tx inside multicall (as other similar txs):**
https://etherscan.io/tx/0xc9e6d8166e9b2d86f7f13d068121afa80fe08b6ecde0106d5e32475254f934d2

**or just bare mint:**
https://etherscan.io/tx/0xb77f348b9a79933b5f11fb21789365707d1985bc40ff1c1ddfb264539c0acc68

I approved both tokens, have enough of both tokens on the account, deadline is in a few years, lower ticks and upper ticks are min and max values, minTokens are zeros. According to the manual tx should pass. But it fails. Can someone help please?

upd.
PAXG is a fee-on-transfer token. Maybe this is the problem?

**Comment by zemse** [comment]
> PAXG is a fee-on-transfer token. Maybe this is the problem?

Yep, there would be an issue when someone is selling PAXG to the pool or adding liquidity in a range where PAXG amount is not zero, because Uniswap's contract will try to `transferFrom` assets and the Pool's balance will increase by less amount, hence the [checks](https://github.com/Uniswap/v3-core/blob/8f3e4645a08850d2335ead3d1a8d0c64fa44f222/contracts/UniswapV3Pool.sol#L483-L484) would fail.

You can still create a Wrapped PAXG ERC20 contract (similar to WETH), so it won't have fees on transfer. Also transferring/swapping WPAXG won't cost their fee-on-transfer as well, though it'd when unwrapping back to PAXG.

**Comment by marktoda** [comment]
Hi @vovapwn - thanks for submitting this! Your intuition was correct; UniswapV3 doesn't support Fee-on-Transfer tokens, as outlined in the docs here https://docs.uniswap.org/protocol/concepts/advanced/integration-issues#fee-on-transfer-tokens.

**Comment by MarkZuckerbergCommunity** [comment]
Need any help ?

**Comment by miohtama** [comment]
As a late note to this discussion, you can now trade [PAXG on Uniwap v3 on Polygon](https://tradingstrategy.ai/trading-view/polygon/uniswap-v3/paxg-usdc-fee-30). This is because bridged or wrapped tokens do not inherit any transfer fee features of their underlying represented token.
